// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application";

import ModalController from "controllers/modal_controller";
application.register("modal", ModalController);

import PostAlertController from "controllers/post_alert_controller";
application.register("post-alert", PostAlertController);

import PostFormController from "controllers/post_form_controller";
application.register("post-form", PostFormController);

import TabsController from "controllers/tabs_controller";
application.register("tabs", TabsController);
