// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PostAlertController from "./post_alert_controller"
application.register("post-alert", PostAlertController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)
