// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application";

import ConditionalFieldsController from "controllers/conditional_fields_controller";
application.register("conditional-fields", ConditionalFieldsController);

import DialogController from "controllers/dialog_controller";
application.register("dialog", DialogController);

import FlashController from "controllers/flash_controller";
application.register("flash", FlashController);

import ModalController from "controllers/modal_controller";
application.register("modal", ModalController);

import PostAlertController from "controllers/post_alert_controller";
application.register("post-alert", PostAlertController);

import PostFormController from "controllers/post_form_controller";
application.register("post-form", PostFormController);

import ScrollResetController from "controllers/scroll_reset_controller";
application.register("scroll-reset", ScrollResetController);

import TabsController from "controllers/tabs_controller";
application.register("tabs", TabsController);
