# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"
    - "db/schema.rb"

Style/AsciiComments:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

Lint:
  Enabled: true

Rails:
  Enabled: true

Security:
  Enabled: true

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
